### ISSUE TITLE
not working .. What I´m doing wrong?

### ISSUE THREAD

**Issue by jesusmoreno1980** [JesusJimenezG/platzidl#13]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--sleep-interval', '180', '--max-sleep-interval', '230', '--limit-rate', '1M', '-o', '%(playlist_index)s-%(chapter_number)s-%(title)s-%(resolution)s.%(ext)s', '--verbose', 'https://platzi.com/clases/2217-pagos-electronicos/35794-la-revolucion-fintech-breve-historia-del-dinero']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.0 (CPython) - Windows-10-10.0.19045-SP0
[debug] exe versions: ffmpeg N-109332-g45ab5307a6-20221201, ffprobe N-109332-g45ab5307a6-20221201
[debug] Proxy map: {}
[Platzi] Downloading login page
[Platzi] Logging in
[Platzi] 35794: Downloading webpage
ERROR: Unable to extract client data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\youtube_dl\extractor\platzi.py", line 109, in _real_extract
    self._search_regex(
  File "C:\Program Files\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract client data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--sleep-interval', '180', '--max-sleep-interval', '230', '--limit-rate', '1M', '-o', '%(playlist_index)s-%(chapter_number)s-%(title)s-%(resolution)s.%(ext)s', '--verbose', 'https://platzi.com/clases/2217-pagos-electronicos/35794-la-revolucion-fintech-breve-historia-del-dinero']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.0 (CPython) - Windows-10-10.0.19045-SP0
[debug] exe versions: ffmpeg N-109332-g45ab5307a6-20221201, ffprobe N-109332-g45ab5307a6-20221201
[debug] Proxy map: {}
[Platzi] Downloading login page
[Platzi] Logging in
ERROR: Unable to extract login; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 533, in extract
    self.initialize()
  File "C:\Program Files\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 437, in initialize
    self._real_initialize()
  File "C:\Program Files\Python311\Lib\site-packages\youtube_dl\extractor\platzi.py", line 26, in _real_initialize
    self._login()
  File "C:\Program Files\Python311\Lib\site-packages\youtube_dl\extractor\platzi.py", line 56, in _login
    self._search_regex(
  File "C:\Program Files\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract login; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Shark1337** [comment]
dont work , proyect dead
