### ISSUE TITLE
No hace login correcto, error al obtener el password en credenciales

### ISSUE THREAD

**Issue by alonsolopezr** [JesusJimenezG/platzidl#8]
Error al login, marca error al introducir usuario, No permite credenciales
```sh
~/code/python/platzidl  master ●                                                    
 $ python platzidl.py
Ingresa tus credenciales de Platzi
Username: mi.usuario@mail.com
Traceback (most recent call last):
  File "platzidl.py", line 197, in <module>
    main()
  File "platzidl.py", line 179, in main
    _get_usr_pw()
  File "platzidl.py", line 26, in _get_usr_pw
    u0 = input("Username: ")
  File "<string>", line 1
    mi.usuario@mail.com
              ^
SyntaxError: invalid syntax
```

**Comment by JonnathanPerez** [comment]
prueba usandolo desde el comando introduciendo los dos argumentos, así es más sencillo
